eureka:
  client:
    serviceUrl:
      # 指定Zone和Server地址的映射; 当有多个zone符合时, 默认选择第一个; 一个zone可以有多个应用,也就是多个Server
      defaultZone: http://localhost:8761/eureka/
    # 指定给当前Client属于哪个Region
    region: china
    # 指定当前应用有哪些可用的Zone
    availability-zones:
      china: defaultZone,hangzhou

  instance:
    prefer-ip-address: true

zuul:
  whitelist:    # zuul白名单配置
    bank-user: localhost,10.36.2.41
               ,0:0:0:0:0:0:0:1

    "forward:/local": 10.36.2.41,0:0:0:0:0:0:0:1

    "http://www.163.com": 10.36.2.41

  filter: baidu,simple

alvis:
  filter: nihao,haha123

name: koui